name: PR Merge

on:
  push:
    branches:
      - "main"

env:
  DOCKER_BUILDKIT: 1
  
jobs:
  codecov:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.10'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.10
      - name: Generate coverage report
        run: |
          pip install -r requirements.txt
          pip install -r tests/requirements.txt
          pytest --cov=./src --cov-report=xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with: 
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build, tag, and push image
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}-${GITHUB_SHA}-$(date +%s)
          docker build -t starpack/starpack-engine:$IMAGE_TAG -t starpack/starpack-engine:latest -f ./docker/starpack.Dockerfile --target prod .
          docker push starpack/starpack-engine

