name: PR Merge

on:
  push:
    branches:
      - "main"

env:
  DOCKER_BUILDKIT: 1
  
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.10.7"
      - name: Generate coverage report
        run: |
          pip install -r requirements.txt
          pip install -r src/tests/requirements.txt
          pytest --cov-report=xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with: 
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build and tag image
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}-${GITHUB_SHA}-$(date +%s)
          docker build -t starpack/starpack-engine:$IMAGE_TAG -t starpack/starpack-engine:latest -f ./docker/starpack.Dockerfile --target prod .
          
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker Hub Push image
        run:
          docker push starpack/starpack-engine -a

